#pragma once

#include <string>

struct Kaomoji {
public:
  std::string name;
  std::string text;

  bool operator==(const Kaomoji& other) const {
    return name == other.name;
  }

  operator bool() const {
    return text != "";
  }
};

const Kaomoji kaomojis[] = {
  {"grinning", u8"(* ^ ω ^)"},
  {"grinning", u8"(≧◡≦)"},
  {"grinning_with_arms", u8"ヽ(o^ ^o)ﾉ"},
  {"grinning", u8"(*≧ω≦*)"},
  {"grinning_with_arms", u8"(๑˃ᴗ˂)ﻭ"},
  {"grinning", u8"(ﾉ≧ڡ≦)"},

  {"sweat_smile", u8"(´･ᴗ･ ` )"},

  {"laughing", u8"(o^▽^o)"},
  {"laughing", u8"(＾▽＾)"},
  {"laughing_with_arms", u8"ヽ(o＾▽＾o)ノ"},
  {"laughing_with_arms", u8"\\(^ヮ^)/"},
  {"laughing_blush", u8"(〃＾▽＾〃)"},

  {"joy", u8"＼(≧▽≦)／"},
  {"joy", u8"{*≧∀≦}"},

  {"satisfied", u8"<(￣︶￣)>"},
  {"satisfied", u8"(￣ω￣)"},
  {"satisfied", u8"(─‿‿─)"},
  {"satisfied_laughing", u8"(￣▽￣)"},
  {"satisfied_laughing_with_arms", u8"＼(￣▽￣)／"},

  {"smiling_with_arms", u8"ヽ(*・ω・)ﾉ"},
  {"smiling_blush", u8"(*^‿^*)"},
  {"smiling", u8"(◕‿◕)"},
  {"relaxed", u8"(๑˘︶˘๑)"},
  {"smiling", u8"(.❛ ᴗ ❛.)"},
  {"smiling_blush", u8"(=^_^=)"},

  {"wink_heart", u8" ღゝ◡╹)ノ♡"},

  {"blush_smile", u8"(*^_^*)"},
  {"flushed", u8"(•ﾟдﾟ•)"},
  {"blush_closed_eyes", u8"(〃￣ω￣〃ゞ"},
  {"blush_smile", u8"(⁄ ⁄•⁄ω⁄•⁄ ⁄)"},
  {"blush_grinning", u8"(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)"},
  {"blush_heart", u8"(´,,•ω•,,)♡"},
  {"blush", u8"米＾－＾米"},

  {"smug", u8"(￢‿￢ )"},

  {"heart_eyes_with_arms", u8"ヽ(♡‿♡)ノ"},
  {"heart_eyes", u8"(*♡∀♡)"},
  {"heart_eyes", u8"٩(♡ε♡)۶"},
  {"heart_eyes", u8"(｡♥‿♥｡)"},
  {"heart_eyes_flower_cheeks", u8"(✿ ♥‿♥)"},
  {"heart_eyes", u8"(๑♡⌓♡๑)"},

  {"star_struck", u8"(✪‿✪)ノ"},
  {"star_struck", u8"(☆▽☆)"},
  {"star_struck", u8"(╯✧▽✧)╯"},

  {"kissing_heart", u8"(っ˘з(˘⌣˘ ) ♡"},
  {"kissing_heart", u8"σ(≧ε≦σ) ♡"},

  {"kissing", u8"(ﾉ´ з `)ノ"},
  {"kissing_closed_eyes", u8"(￣ε￣＠)"},
  {"kissing_closed_eyes", u8"(￣З￣)"},
  {"kissing", u8"(ɔˆз(ˆ⌣ˆc)"},

  {"smiling_with_tear", u8"أ‿أ"},

  {"heart_cheeks", u8"(♡-_-♡)"},
  {"heart_cheeks", u8"(´ ω `♡)"},
  {"heart_cheeks_smiling", u8"(ღ˘⌣˘ღ)"},
  {"heart_cheeks_laughing", u8"(♡°▽°♡)"},
  {"heart_cheeks", u8"（♥￫ｏ￩♥）"},

  {"couple", u8"( ˘⌣˘)♡(˘⌣˘ )"},
  {"blush_heart_arrow", u8"Σ>―(〃°ω°〃)♡→"},
  {"share_hearts", u8"♡＼(￣▽￣)／♡"},

  {"flower_cheeks_smiling", u8"(✿╹◡╹)"},
  {"flower_cheeks", u8"(◕‿◕✿)"},
  {"flower_cheeks", u8"(ㆁᴗㆁ✿)"},
  {"flower_cheeks_grinning", u8"(≖ᴗ≖✿)"},
  {"flower_cheeks", u8"(✿ヘᴥヘ)"},

  {"OwO", u8"♡(ŐωŐ人)"},

  {"peace", u8"y（^ヮ^）y"},

  {"thumbs_up", u8"PLACEHOLDER"},
  {"thumbs_up", u8"d(^^*)"},

  {"expressionless", u8"|*￣ー￣|"},
  {"expressionless", u8"（￣ε￣）"},

  {"cry", u8"(ಥ﹏ಥ)"},
  {"cry", u8"╥﹏╥"},
  {"cry", u8"（ｉДｉ）"},
  {"cry", u8"༼ಢ_ಢ༽"},

  {"sob", u8".･ﾟﾟ･(／ω＼)･ﾟﾟ･."},
  {"sob", u8"｡･ﾟﾟ*(>д<)*ﾟﾟ･｡"},

  {"sad", u8"(⋟﹏⋞)"},
  {"confused", u8"(☍﹏⁰)｡"},
  {"frowning", u8"(-_-)"},
  {"sad_disappointed", u8"(｡╯︵╰｡)"},
  {"sad_disappointed", u8"(｡•́︿•̀｡)"},

  {"hugging_sad", u8"(っ˘̩╭╮˘̩)っ"},

  {"not_sure_tear", u8"(≖͞_≖̥)"},

  {"unamused", u8"(；⌣̀_⌣́)"},

  {"unamused", u8"(￢_￢;)"},
  {"unamused", u8"(￣ヘ￣)"},
  {"unamused", u8"(¬▂¬)"},

  {"argueing", u8"(；￣Д￣)"},
  {"argueing", u8"(」°ロ°)」"},
  {"argueing", u8"ヾ( ￣O￣)ツ"},

  {"confounded", u8"(〃＞＿＜;〃)"},
  {"confounded", u8"(＞﹏＜)"},

  {"praying", u8"(￣人￣)"},
  {"praying", u8"(uωu人)"},

  {"pleading_wink", u8"(人ゝω・）"},
  {"pleading", u8"((_　_*"},
  {"pleading", u8"(」ﾟДﾟ」"},
  {"pleading", u8"(人ФｴФ)"},

  {"cat", u8"(=ↀωↀ=)"},
  {"cat", u8"(⁎˃ᆺ˂)"},
  {"cat", u8"(=ＴェＴ=)"},
  {"cat", u8"ฅ(≚ᄌ≚)"},

  {"worried", u8"(ó﹏ò｡)"},
  {"worried", u8"(´･_･｀)"},

  {"pout", u8"( ￣＾￣)"},
  {"pout", u8"( *｀з´)"},

  {"mad", u8"ಠ_ಠ"},
  {"mad_with_arms", u8"ノಠ_ಠノ"},
  {"mad", u8"ಠ▃ಠ"},

  {"angry", u8"(⋋▂⋌)"},
  {"angry", u8"〴⋋_⋌〵"},
  {"angry", u8"(◔ д◔)"},
  {"angry", u8"(ʘдʘ╬)"},
  {"angry", u8"(╬ಠ益ಠ)"},

  {"cheerleader", u8"⁽⁽⁕◟(.öˬö.)◞⁕⁾⁾"},
  {"cheerleader", u8"✺◟(∗❛ัᴗ❛ั∗)◞✺"},

  {"party", u8"┗( ^o^)┛≡┏( ^o^)┓≡┗( ^o^)┛"},
  {"party", u8"╭(°ㅂ°)╮╰(°ㅂ°)╯╭(°ㅂ°)╮╰(°ㅂ°)╯"},
  {"party", u8"♪♪＼(^ω^＼)( /^ω^)/♪♪"},

  {"couple_dancing", u8"♪～(◔◡◔ิ)人(╹◡╹๑)～♪"},
  {"couple_dancing", u8"ヽ(○｀･v･)人(･v･´●)ﾉ"},

  {"dancing", u8"┌|≧∇≦|┘"},
  {"dancing", u8"(〜￣△￣)〜"},
  {"dancing", u8"ヘ(￣ω￣ヘ)"},
  {"dancing", u8"₍₍ ◝(・ω・)◟ ⁾⁾"},

  {"take_my_energy", u8"༼ つ ◕_◕ ༽つ"},
  {"shrugging", u8"¯\\_(ツ)_/¯"},
  {"sniper", u8"( ´-ω･)︻┻┳══━一"},
  {"dog", u8"◤◡ᴥ◡◥ "},
  {"disapproval", u8"ಠ_ಠ"},
  {"doing_homework", u8"＿φ(°-°=)"},
  {"thumbs_up", u8"d-(^.^)z"},
  {"annoyed", u8"(¬_¬\")"},
  {"flipping_table", u8"(╯°□°)╯︵ ┻━┻"},
  {"deal_with_it", u8"(▀̿Ĺ̯▀̿ ̿)"},
  {"distraught", u8"༼ ༎ຶ ෴ ༎ຶ༽"},
  {"overjoyed", u8"^_^"},
  {"dancing", u8"♪┏(・o･)┛♪"},
  {"butterfly", u8"Ƹ̵̡Ӝ̵̨̄Ʒ"},
  {"kitty_cat", u8"⋟^≏^⋞"},
  {"table_flips_you", u8"┬─┬﻿︵/(.□.)╯"},
  {"kirby", u8"(っ^‿^)っ"},
  {"shocked", u8"⊙▂⊙"},
  {"polar_bear", u8"ʕ•͡ᴥ•ʔ"},
  {"kyubey", u8"／人◕ ‿‿ ◕人＼"},
  {"crazy", u8"(◐‿◑)﻿"},
  {"feisty", u8"(ง •̀_•́)ง"},
  {"buddies", u8"(*^o^)人(^o^*)"},
  {"walrus", u8"(:3 っ)っ"},
  {"worried", u8"(´╹〽╹`)"},
  {"wizard", u8"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"cat", u8"ฅ(=＾◕ᆺ◕＾=)ฅ"},
  {"hug_me", u8"⊂((・▽・))⊃"},
  {"scared", u8".∵･(ﾟДﾟ)"},
  {"herp_derp", u8"（。々°）"},
  {"spongebob_squarepants", u8"|∴め ϖ め∴|"},
  {"sword_fighting", u8"(´>_●)メ(●_<｀)"},
  {"koala", u8"ʕ •ᴥ•ʔ"},
  {"frosty_the_snowman", u8"ᒄ₍⁽ˆ⁰ˆ⁾₎ᒃ♪♬"},
  {"loving", u8"(ɔ◔‿◔)ɔ ♥"},
  {"but_at_what_cost", u8"ლ(ಠ益ಠლ)"},
  {"lenny", u8"( ͡° ͜ʖ ͡°)"},
  {"gimme", u8"༼ つ ◕_◕ ༽つ"},
  {"painful", u8"(>_<)"},
  {"whoops", u8"(－‸ლ)"},
  {"confused", u8"¯\\(°_o)/¯"},
  {"bowling", u8"＝( ^o^)ノ___ｏ"},
  {"yoo-hoo", u8"(ﾉﾟ0ﾟ)ﾉ~"},
  {"ghost", u8"(((༼•̫͡•༽)))"},
  {"puppy", u8"U＾ェ＾U"},
  {"flipping_table", u8"┻━┻ ︵ ヽ(°□°ヽ)"},
  {"flexing", u8"ᕦ(ò_óˇ)ᕤ"},
  {"superhero", u8"─=≡Σ(([ ⊐•̀⌂•́]⊐"},
  {"zombie", u8"[¬º-°]¬"},
  {"celebrating", u8"ᕕ( ᐛ )ᕗ"},
  {"mustache", u8"( ￣┏＿┓￣)"},
  {"happy", u8"^-^"},
  {"staring", u8"(;￢_￢)"},
  {"punching", u8"(o￣∇￣)=◯)`ν゜)･"},
  {"fish", u8"ϵ( 'Θ' )϶"},
  {"squid", u8"<コ:彡"},
  {"giving_up", u8"(;´Д`)"},
  {"unimpressed", u8"（￣～￣）"},
  {"shy", u8"（/｡＼)"},
  {"monocle", u8"ಠ_ರೃ"},
  {"running", u8"ε=┏(ﾟロﾟ;)┛"},
  {"furious", u8"(ò_ó)"},
  {"hugging", u8"(>^_^)><(^o^<)"},
  {"huh", u8"[•.•ิ]"},
  {"pumped", u8"o(^▽^)o"},
  {"octopus", u8"Ｃ:。ミ"},
  {"peace", u8"(^o^)y"},
  {"unamused", u8"(ㆆ_ㆆ)"},
  {"playing_in_the_snow", u8"◦°˚\\☺/˚°◦"},
  {"sleeping", u8"(–˛ — º)"},
  {"emo", u8"(//_^)"},
  {"anticipation", u8"(⊃‿⊂)"},
  {"thinking", u8"(p_-)"},
  {"teddy_bear", u8"⊂(◜ᴥ◝)つ"},
  {"guilty", u8"^_^;"},
  {"anime_sweat_drop", u8"-_-;"},
  {"doing_homework", u8"＿φ( °-°)/"},
  {"devastated", u8"(ಥ﹏ಥ)"},
  {"panda", u8"◖㈠ ω ㈠◗"},
  {"lurk", u8"┬┴┬┴┤(･_├┬┴┬┴"},
  {"seal", u8"(ᵔᴥᵔ)"},
  {"excited", u8"ヽ(★ω★)ノ"},
  {"magic_attack", u8"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"sobbing", u8"(╥﹏╥)"},
  {"snubbing", u8"(´･ω･`)"},
  {"anger", u8"ლ(ಠ益ಠ)ლ"},
  {"angry_flailing", u8"ヽ(｀⌒´メ)ノ"},
  {"crying", u8"T^T"},
  {"pig", u8"<(^oo^)>"},
  {"freak_out", u8"ヽ(ﾟДﾟ)ﾉ"},
  {"sleeping_kirby", u8"૮(-.-)ა"},
  {"content", u8"˙ ͜ʟ˙"},
  {"resign", u8"(;-_-)ノ"},
  {"chasing", u8"(○｀д´)ﾉｼ Σ(っﾟДﾟ)っ"},
  {"bird", u8"(●∈∋●)"},
  {"hug", u8"(っ⌒‿⌒)っ"},
  {"ashamed", u8"(；一_一)"},
  {"darth_vader", u8"(｡▼皿▼)"},
  {"dj", u8"d^_^b"},
  {"bear", u8"⊂(￣(ｴ)￣)⊃"},
  {"oh_no!", u8"L(´□｀L)"},
  {"inquisitive", u8"(╭ರ_•́)"},
  {"monocle", u8"(╭ರ_•́)"},
  {"sleepy", u8"(- o - ) zzZ ☽"},
  {"whispering", u8"( ￣ﾉ∇￣)￣ｰ￣)"},
  {"gleeful", u8"｡◕‿◕｡"},
  {"on_the_phone", u8"(〃＾∇＾)】"},
  {"disgruntled", u8"( ͡° ʖ̯ ͡°)"},
  {"clown", u8"⫷ °⧭° ⫸"},
  {"bunny", u8"(=^_^=)"},
  {"psycho", u8"ヘ（。□°）ヘ"},
  {"arm_wrestle", u8"( `_)乂(_' )"},
  {"groggy", u8"(-_ゞ"},
  {"bow_and_arrow", u8"<( ･ｪ-)<}"},
  {"pigtails", u8"∋∞(●ﾟvﾟ)∞∈"},
  {"bro_pound", u8"(ó ì_í)=óò=(ì_í ò)"},
  {"scheming", u8"ಠᴗಠ"},
  {"muscular_person", u8"ᕦ❍ᴗ❍ᕤ"},
  {"bawling", u8"ಥ_ಥ"},
  {"skeptical", u8"(•͡.•͡)"},
  {"rolling_eyes", u8"◔̯◔"},
  {"imbecile", u8"(＊☉౪ ⊙｡)ﾉ"},
  {"bread", u8"ʕʔ"},
  {"hiding", u8"|д･)"},
  {"scaring", u8"(☄ฺ◣д◢)☄ฺ"},
  {"smoking", u8"y(^ o^)y~~"},
  {"hiding_easter_eggs", u8"( • ∀•)っθΘʘ"},
  {"embarrassed", u8"(#^.^#)"},
  {"dead_person", u8"✖‿✖"},
  {"frustrated", u8"(ᗒᗣᗕ)"},
  {"happy_crying", u8"(°̥̥̥̥̥̥̥̥ᴗ°̥̥̥̥̥̥̥̥)"},
  {"fighting", u8"(ง •̀ゝ•́)ง"},
  {"syringe", u8"-{'''|'''|'''|''']=[]"},
  {"glad", u8"＼（＾ ＾）／"},
  {"bat", u8"/|\\( ;,; )/|\\"},
  {"beaten_up", u8"(*@_＊#)"},
  {"writing", u8"＿〆(。。)"},
  {"best_buds", u8"（　＾＾）人（＾＾　）"},
  {"fu_manchu_man", u8"(￣┏∞┓￣)"},
  {"pumped_up", u8"ヽ( ★ω★)ノ"},
  {"waving", u8"( ^_^)／"},
  {"whatever", u8"¬.¬"},
  {"kiss_me", u8"( ˘ ³˘)♥"},
  {"pucker_up", u8"（*＾3＾）"},
  {"lethargic", u8"(‾ʖ̫‾)"},
  {"surrender", u8"(ﾉ_ _)ﾉ"},
  {"gift", u8"(´・ω・)っ由"},
  {"weary", u8"(´~`)"},
  {"chameleon", u8"ᘛ⁐̤ᕐᐷ"},
  {"tired", u8"〠_〠"},
  {"rabbit", u8"U=･ x ･=U"},
  {"infatuated", u8"（*´▽｀*）"},
  {"table_tennis", u8"‎(>o<)ρミ┳┷┳゜"},
  {"whistling", u8"♪～(￣ε￣；)"},
  {"dreaming", u8"(_ _)..ooOO"},
  {"deceased", u8"(✖╭╮✖)"},
  {"painting", u8"(。･_･)ノ”【】"},
  {"pikachu", u8"(o^-^o)"},
  {"bear_cub", u8"(ó㉨ò)"},
  {"boogie_down", u8"ヽ(⌐■_■)ノ♪♬"},
  {"winnie_the_pooh", u8"ʕ •́؈•̀)"},
  {"reluctant", u8"o(´^｀)o"},
  {"surprised", u8"（￣□￣；）"},
  {"shooting", u8"(ﾟ皿ﾟ)ｒ┏┳－*"},
  {"thank_you", u8"＼(-_- )"},
  {"phone", u8"(((☎)))"},
  {"couple_kissing", u8"(* ￣)(￣ *) "},
  {"olympic_hammer_throw", u8"(ﾉ-o-)ﾉ 中"},
  {"cunning", u8"(¬‿¬)"},
  {"puzzled", u8"「(°ヘ°)"}
};
