#pragma once

#include <string>

struct Kaomoji {
public:
  std::string name;
  std::string text;

  bool operator==(const Kaomoji& other) const {
    return name == other.name;
  }

  operator bool() const {
    return text != "";
  }
};

// generated from https://slangit.com/emoticons/kaomoji
const Kaomoji kaomojis[] = {
  {"take_my_energy", u8"༼ つ ◕_◕ ༽つ"},
  {"shrugging", u8"¯\\_(ツ)_/¯"},
  {"sniper", u8"( ´-ω･)︻┻┳══━一"},
  {"dog", u8"◤◡ᴥ◡◥ "},
  {"disapproval", u8"ಠ_ಠ"},
  {"doing_homework", u8"＿φ(°-°=)"},
  {"thumbs_up", u8"d-(^.^)z"},
  {"annoyed", u8"(¬_¬\")"},
  {"flipping_table", u8"(╯°□°)╯︵ ┻━┻"},
  {"deal_with_it", u8"(▀̿Ĺ̯▀̿ ̿)"},
  {"distraught", u8"༼ ༎ຶ ෴ ༎ຶ༽"},
  {"overjoyed", u8"^_^"},
  {"dancing", u8"♪┏(・o･)┛♪"},
  {"doggy", u8"V●ᴥ●V"},
  {"outlaw", u8"̿’̿’\\̵͇̿̿\\З=( ͠° ͟ʖ ͡°)=Ε/̵͇̿̿/’̿̿ ̿ ̿ ̿ ̿ ̿"},
  {"laughing", u8"(＾▽＾)"},
  {"butterfly", u8"Ƹ̵̡Ӝ̵̨̄Ʒ"},
  {"joyful", u8"(≧∇≦)/"},
  {"stereo", u8"|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|"},
  {"kitty_cat", u8"⋟^≏^⋞"},
  {"table_flips_you", u8"┬─┬﻿︵/(.□.)╯"},
  {"kirby", u8"(っ^‿^)っ"},
  {"shocked", u8"⊙▂⊙"},
  {"polar_bear", u8"ʕ•͡ᴥ•ʔ"},
  {"kyubey", u8"／人◕ ‿‿ ◕人＼"},
  {"crazy", u8"(◐‿◑)﻿"},
  {"feisty", u8"(ง •̀_•́)ง"},
  {"buddies", u8"(*^o^)人(^o^*)"},
  {"walrus", u8"(:3 っ)っ"},
  {"worried", u8"(´╹〽╹`)"},
  {"wizard", u8"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"cat", u8"ฅ(=＾◕ᆺ◕＾=)ฅ"},
  {"hug_me", u8"⊂((・▽・))⊃"},
  {"flipping_facebook", u8"(╯°□°)╯︵ ʞooqǝɔɐɟ"},
  {"scared", u8".∵･(ﾟДﾟ)"},
  {"herp_derp", u8"（。々°）"},
  {"snowing", u8"❆❅❉"},
  {"spongebob_squarepants", u8"|∴め ϖ め∴|"},
  {"sword_fighting", u8"(´>_●)メ(●_<｀)"},
  {"koala", u8"ʕ •ᴥ•ʔ"},
  {"frosty_the_snowman", u8"ᒄ₍⁽ˆ⁰ˆ⁾₎ᒃ♪♬"},
  {"loving", u8"(ɔ◔‿◔)ɔ ♥"},
  {"but_at_what_cost", u8"ლ(ಠ益ಠლ)"},
  {"smiling", u8"( ͡° ͜ʖ ͡°)"},
  {"gimme", u8"༼ つ ◕_◕ ༽つ"},
  {"painful", u8"(>_<)"},
  {"whoops", u8"(－‸ლ)"},
  {"confused", u8"¯\\(°_o)/¯"},
  {"bowling", u8"＝( ^o^)ノ___ｏ"},
  {"yoo-hoo", u8"(ﾉﾟ0ﾟ)ﾉ~"},
  {"ghost", u8"(((༼•̫͡•༽)))"},
  {"puppy", u8"U＾ェ＾U"},
  {"flipping_table", u8"┻━┻ ︵ ヽ(°□°ヽ)"},
  {"flexing", u8"ᕦ(ò_óˇ)ᕤ"},
  {"superhero", u8"─=≡Σ(([ ⊐•̀⌂•́]⊐"},
  {"zombie", u8"[¬º-°]¬"},
  {"celebrating", u8"ᕕ( ᐛ )ᕗ"},
  {"mustache", u8"( ￣┏＿┓￣)"},
  {"happy", u8"^-^"},
  {"staring", u8"(;￢_￢)"},
  {"punching", u8"(o￣∇￣)=◯)`ν゜)･"},
  {"fish", u8"ϵ( 'Θ' )϶"},
  {"squid", u8"<コ:彡"},
  {"giving_up", u8"(;´Д`)"},
  {"unimpressed", u8"（￣～￣）"},
  {"shy", u8"（/｡＼)"},
  {"monocle", u8"ಠ_ರೃ"},
  {"in_love", u8"(♥_♥)"},
  {"running", u8"ε=┏(ﾟロﾟ;)┛"},
  {"furious", u8"(ò_ó)"},
  {"hugging", u8"(>^_^)><(^o^<)"},
  {"huh", u8"[•.•ิ]"},
  {"hippie", u8"(✿◠‿◠) "},
  {"pumped", u8"o(^▽^)o"},
  {"octopus", u8"Ｃ:。ミ"},
  {"peace", u8"(^o^)y"},
  {"unamused", u8"(ㆆ_ㆆ)"},
  {"playing_in_the_snow", u8"◦°˚\\☺/˚°◦"},
  {"sleeping", u8"(–˛ — º)"},
  {"emo", u8"(//_^)"},
  {"cyclops", u8"๏-)"},
  {"anticipation", u8"(⊃‿⊂)"},
  {"thinking", u8"(p_-)"},
  {"teddy_bear", u8"⊂(◜ᴥ◝)つ"},
  {"guilty", u8"^_^;"},
  {"anime_sweat_drop", u8"-_-;"},
  {"doing_homework", u8"＿φ( °-°)/"},
  {"devastated", u8"(ಥ﹏ಥ)"},
  {"panda", u8"◖㈠ ω ㈠◗"},
  {"snooper", u8"┬┴┬┴┤(･_├┬┴┬┴"},
  {"seal", u8"(ᵔᴥᵔ)"},
  {"excited", u8"ヽ(★ω★)ノ"},
  {"magic_attack", u8"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"sobbing", u8"(╥﹏╥)"},
  {"high_five", u8"^_^/"},
  {"snubbing", u8"(´･ω･`)"},
  {"anger", u8"ლ(ಠ益ಠ)ლ"},
  {"angry", u8"ヽ(｀⌒´メ)ノ"},
  {"crying", u8"T^T"},
  {"pig", u8"<(^oo^)>"},
  {"freak_out", u8"ヽ(ﾟДﾟ)ﾉ"},
  {"sleeping_kirby", u8"૮(-.-)ა"},
  {"content", u8"˙ ͜ʟ˙"},
  {"giving_up", u8"(;-_-)ノ"},
  {"chasing", u8"(○｀д´)ﾉｼ Σ(っﾟДﾟ)っ"},
  {"bird", u8"(●∈∋●)"},
  {"hug", u8"(っ⌒‿⌒)っ"},
  {"ashamed", u8"(；一_一)"},
  {"darth_vader", u8"(｡▼皿▼)"},
  {"dj", u8"d^_^b"},
  {"bear", u8"⊂(￣(ｴ)￣)⊃"},
  {"oh_no!", u8"L(´□｀L)"},
  {"inquisitive", u8"(╭ರ_•́)"},
  {"sad", u8"T.T"},
  {"sleepy", u8"(- o - ) zzZ ☽"},
  {"whispering", u8"( ￣ﾉ∇￣)￣ｰ￣)"},
  {"gleeful", u8"｡◕‿◕｡"},
  {"on_the_phone", u8"(〃＾∇＾)】"},
  {"disgruntled", u8"( ͡° ʖ̯ ͡°)"},
  {"clown", u8"⫷ °⧭° ⫸"},
  {"bunny", u8"(=^_^=)"},
  {"psycho", u8"ヘ（。□°）ヘ"},
  {"arm_wrestle", u8"( `_)乂(_' )"},
  {"groggy", u8"(-_ゞ"},
  {"bow_and_arrow", u8"<( ･ｪ-)<}"},
  {"pigtails", u8"∋∞(●ﾟvﾟ)∞∈"},
  {"bro_pound", u8"(ó ì_í)=óò=(ì_í ò)"},
  {"scheming", u8"ಠᴗಠ"},
  {"muscular_person", u8"ᕦ❍ᴗ❍ᕤ"},
  {"bawling", u8"ಥ_ಥ"},
  {"skeptical", u8"(•͡.•͡)"},
  {"rolling_eyes", u8"◔̯◔"},
  {"imbecile", u8"(＊☉౪ ⊙｡)ﾉ"},
  {"bread", u8"ʕʔ"},
  {"playstation_portable", u8"(+[__]∙:∙)"},
  {"hiding", u8"|д･)"},
  {"scaring", u8"(☄ฺ◣д◢)☄ฺ"},
  {"smoking", u8"y(^ o^)y~~"},
  {"hiding_easter_eggs", u8"( • ∀•)っθΘʘ"},
  {"embarrassed", u8"(#^.^#)"},
  {"dead_person", u8"✖‿✖"},
  {"frustrated", u8"(ᗒᗣᗕ)"},
  {"happy_crying", u8"(°̥̥̥̥̥̥̥̥ᴗ°̥̥̥̥̥̥̥̥)"},
  {"putting_facebook_back_after_flipping_it", u8"Facebookノ( º _ ºノ)"},
  {"fighting", u8"(ง •̀ゝ•́)ง"},
  {"syringe", u8"-{'''|'''|'''|''']=[]"},
  {"glad", u8"＼（＾ ＾）／"},
  {"bat", u8"/|\\( ;,; )/|\\"},
  {"beaten_up", u8"(*@_＊#)"},
  {"writing", u8"＿〆(。。)"},
  {"best_buds", u8"（　＾＾）人（＾＾　）"},
  {"fu_manchu_man", u8"(￣┏∞┓￣)"},
  {"pumped_up", u8"ヽ( ★ω★)ノ"},
  {"waving", u8"( ^_^)／"},
  {"whatever", u8"¬.¬"},
  {"kiss_me", u8"( ˘ ³˘)♥"},
  {"pucker_up", u8"（*＾3＾）"},
  {"lethargic", u8"(‾ʖ̫‾)"},
  {"surrender", u8"(ﾉ_ _)ﾉ"},
  {"gift", u8"(´・ω・)っ由"},
  {"weary", u8"(´~`)"},
  {"chameleon", u8"ᘛ⁐̤ᕐᐷ"},
  {"tired", u8"〠_〠"},
  {"rabbit", u8"U=･ x ･=U"},
  {"infatuated", u8"（*´▽｀*）"},
  {"table_tennis", u8"‎(>o<)ρミ┳┷┳゜"},
  {"whistling", u8"♪～(￣ε￣；)"},
  {"dreaming", u8"(_ _)..ooOO"},
  {"deceased", u8"(✖╭╮✖)"},
  {"painting", u8"(。･_･)ノ”【】"},
  {"pikachu", u8"(o^-^o)"},
  {"bear_cub", u8"(ó㉨ò)"},
  {"boogie_down", u8"ヽ(⌐■_■)ノ♪♬"},
  {"winnie_the_pooh", u8"ʕ •́؈•̀)"},
  {"reluctant", u8"o(´^｀)o"},
  {"surprised", u8"（￣□￣；）"},
  {"shooting", u8"(ﾟ皿ﾟ)ｒ┏┳－*"},
  {"thank_you", u8"＼(-_- )"},
  {"phone", u8"(((☎)))"},
  {"kissing", u8"(* ￣)(￣ *) "},
  {"olympic_hammer_throw", u8"(ﾉ-o-)ﾉ 中"},
  {"cunning", u8"(¬‿¬)"},
  {"puzzled", u8"「(°ヘ°)"}
};
  